const podcastsData = [
    {
      name: "Dritte Halbzeit",
      link: "https://podcasts.apple.com/ch/podcast/dritte-halbzeit/id1472567168",
      info: "Der Podcast zum Schweizer Fussball.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts124/v4/54/8e/06/548e062f-c556-8add-8aa9-cbfa6593c129/mza_7447339559796917482.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "60 min",
      thema: "Sport",
      art: "Episodisch",
      letzte: "23. Oktober 2023"
    },
    {
      name: "Blick: Pro und Konter",
      link: "https://podcasts.apple.com/ch/podcast/blick-pro-und-konter/id1438611005",
      info: "Bei «Pro und Konter» diskutieren wöchentlich die beiden Blick-Sportredaktoren Emanuel Gisi und Dino Kessler über das Spannendste aus der Welt des Sports. Hinweis der Redaktion: Bei Kessler handelt es sich im übrigen tatsächlich um den ehemaligen Bündner Hockey-Profi.<br/><br/>Produktion: Carlo Lardi",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/59/f2/90/59f290a7-6367-c6b1-369c-1fecb29b5895/mza_17132771826203359250.jpg/626x0w.jpg",
      verlag: "Blick",
      dauer: "60 min",
      thema: "Sport",
      art: "Episodisch",
      letzte: "24. Oktober 2023"
    },
    {
      name: "Ehrenrunde - der Fussball Podcast",
      link: "https://podcasts.apple.com/ch/podcast/ehrenrunde-der-fussball-podcast/id1451574295",
      info: "Stefan Büsser und Manuel Rothmund reden mit ihren Gästen über die Lage der Fussballnation Schweiz.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/86/91/b1/8691b100-155b-298f-cc96-446187d6ddb1/mza_14503717423059313253.png/626x0w.png",
      verlag: "Blue",
      dauer: "45 min",
      thema: "Sport",
      art: "Episodisch",
      letzte: "23. Oktober 2023"
    },
    {
      name: "Apropos – der tägliche Podcast des Tages-Anzeigers",
      link: "https://podcasts.apple.com/ch/podcast/apropos-der-t%C3%A4gliche-podcast-des-tages-anzeigers/id1560227032",
      info: "Politisch, persönlich, nah: Der tägliche Podcast des Tages-Anzeigers und der Redaktion Tamedia beleuchtet aktuelle Themen und Geschichten, die zu reden geben. Von Montag bis Freitag – präsentiert von Mirja Gabathuler und Philipp Loser.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/13/10/9a/13109ab7-adb3-cc3e-bddd-797a9c64cfa2/mza_16980135901579536403.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "30 min",
      thema: "Nachrichten",
      art: "Episodisch",
      letzte: "26. Oktober 2023"
    },
    {
      name: "NZZ Akzent",
      link: "https://podcasts.apple.com/ch/podcast/nzz-akzent/id1506761994",
      info: "Täglich erzählen NZZ-Korrespondentinnen und Redaktoren, was sie bewegt: Geschichten aus der ganzen Welt inklusive fundierter Analyse aus dem Hause NZZ, in rund 15 min erzählt. Das ist «NZZ Akzent» – täglich ein Stück Welt.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/57/d2/53/57d2531f-9d33-fbfb-3e37-1f3a05270f29/mza_15244313429225534694.jpg/626x0w.jpg",
      verlag: "NZZ",
      dauer: "15 min",
      thema: "Nachrichten",
      art: "Episodisch",
      letzte: "26. Oktober 2023"
    },
    {
      name: "Dritte Gewalt – der Justiz-Podcast der Republik",
      link: "https://podcasts.apple.com/ch/podcast/dritte-gewalt-der-justiz-podcast-der-republik/id1713125963",
      info: "Was ist ein Kronzeuge? Wann ist ein Verfahren öffentlich? Und warum gibt es eigentlich noch ein Militärgericht? Das Schweizer Justizsystem hat seine Tücken – und wenige kennen sie besser als die langjährige Gerichtsreporterin Brigitte Hürlimann. Im Justiz-Podcast «Dritte Gewalt» spricht sie mit ihrem Republik-Kollegen Boas Ruh über ihre spannendsten Fälle.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/7c/14/1b/7c141b78-c7fd-8eb0-0987-aca2e4b1cfd8/mza_14042763393938980238.jpg/626x0w.jpg",
      verlag: "Republik",
      dauer: "30 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "18. Oktober 2023"
    },
    {
      name: "ZwägHochZwei – Der kurze Podcast für ein gesundes, langes Leben",
      link: "https://podcasts.apple.com/ch/podcast/zw%C3%A4ghochzwei-der-kurze-podcast-f%C3%BCr-ein-gesundes-langes/id1690051642",
      info: "Sie ist schon Langlebigkeits-Expertin, er kritisch-interessiert: Kurt Aeschbacher (74) und Nina Ruge (67) diskutieren über die neusten Trends, um ein langes und gesundes Leben zu führen. Unterstützt von führenden Wissenschaftlern. Es geht um Schlaf, Gemüse und Eisbaden!",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/ae/a6/7d/aea67db8-f197-0c15-d1c8-ac09be0e2b88/mza_10025274302583388475.jpg/626x0w.jpg",
      verlag: "Blick",
      dauer: "30 min",
      thema: "Wissen",
      art: "Episodisch",
      letzte: "25. Oktober 2023"
    },
    {
      name: "Politbüro",
      link: "https://podcasts.apple.com/ch/podcast/politb%C3%BCro/id1510985934",
      info: "Der Tamedia-Podcast zur Schweizer Politik.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts124/v4/09/d8/a1/09d8a1e5-940d-2a2d-8cbf-94b093d69c95/mza_5194469961885084291.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "45 min",
      thema: "Politik",
      art: "Episodisch",
      letzte: "22. Oktober 2023"
    },
    {
      name: "NZZ Megahertz",
      link: "https://podcasts.apple.com/ch/podcast/nzz-megahertz/id1687094460",
      info: "Ist die monogame Beziehung überholt? Sind wir süchtig nach unseren Smartphones? Und ist zu viel Optimismus schädlich? Jeden Donnerstag stellt sich «NZZ Megahertz» den emotionalen und intellektuellen Herausforderungen des Lebens. Jenny Rieger und Oliver Camenzind stellen die Fragen, die in der Luft liegen. Und suchen nach Antworten – mit Gästen, die Bescheid wissen. «NZZ Megahertz» ist neugierig, persönlich und jede Woche frisch.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/d9/48/46/d9484692-02af-8e39-d767-37abf4058cf5/mza_13889778988698407190.jpg/626x0w.jpg",
      verlag: "NZZ",
      dauer: "45 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "25. Oktober 2023"
    },
    // {
    //   name: "Weltwoche Daily",
    //   link: "https://podcasts.apple.com/ch/podcast/weltwoche-daily/id1622583996",
    //   info: "«Weltwoche Daily» – jetzt als Podcast für unterwegs. Steigen Sie ein, hören Sie mit! www.weltwoche.ch<br/> Hosted on Acast. See acast.com/privacy for more information.",
    //   thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts122/v4/4a/b5/37/4ab5374a-2be5-2149-dcb5-82bc2f3b4656/mza_13640473163607749169.jpg/626x0w.jpg",
    //   verlag: "Weltwoche",
    //   dauer: "",
    //   thema: "Nachrichten",
    //   art: "Episodisch",
    //   letzte: "28. Oktober 2023"
    // },
    {
      name: "Anderi Liga",
      link: "https://podcasts.apple.com/ch/podcast/anderi-liga/id1616890092",
      info: "Tore und Taktiken, Transfers und Tumulte: «Anderi Liga», der Fussball-Podcast von 20 Minuten, behandelt die spannendsten Themen im nationalen und internationalen Fussball. 20-min-Sportchef Tobias Wedermann und NZZ-Fussballjournalist Fabian Ruch sprechen über alles, was die Fans bewegt – manchmal mit Gästen, manchmal ohne.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/65/b4/08/65b40855-98c3-77b7-8a7e-64cb92693b6e/mza_1565896493632216246.jpg/626x0w.jpg",
      verlag: "20 Minuten",
      dauer: "60 min",
      thema: "Sport",
      art: "Episodisch",
      letzte: "24. Oktober 2023"
    },
    {
      name: "NZZ Audio",
      link: "https://podcasts.apple.com/ch/podcast/nzz-audio/id1692536576",
      info: "Bildschirm aus. Ohren auf: «NZZ Audio» bietet Ihnen die beeindruckendsten Artikel aus der Welt der NZZ, ausgewählt von unseren Journalistinnen und Journalisten, vorgelesen von professionellen Sprecherinnen und Sprechern.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/PodcastSource126/v4/8b/e6/be/8be6beea-9deb-d274-3cc1-9183ad45c182/597e50fa-360e-4f8f-b880-b712e3a82c37.jpg/626x0w.jpg",
      verlag: "NZZ",
      dauer: "15 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "25. Oktober 2023"
    },
    {
      name: "Alles klar, Amerika?",
      link: "https://podcasts.apple.com/ch/podcast/alles-klar-amerika/id1477466709",
      info: "Der Tamedia-Podcast zu Politik und Alltag in den USA.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/06/e5/74/06e574c7-6566-9e1b-2e47-2fe71c186ead/mza_9718863325068510241.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "30 min",
      thema: "Politik",
      art: "Episodisch",
      letzte: "25. Oktober 2023"
    },
    {
      name: "Republik «Vorgelesen»",
      link: "https://podcasts.apple.com/ch/podcast/republik-vorgelesen/id1613537516",
      info: "Die Republik im Ohr und die Hände frei: auf dem Sofa, im Büro, im Zug oder im Wald. Jede Woche ein neues Highlight.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/6e/76/94/6e7694e5-40d5-e90f-b240-ea1efb759c11/mza_11455834823774965480.jpg/626x0w.jpg",
      verlag: "Republik",
      dauer: "30 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "27. Oktober 2023"
    },
    {
      name: "Der grosse Bluff",
      link: "https://podcasts.apple.com/ch/podcast/der-grosse-bluff/id1643098092",
      info: "Wie Dieter Behring die Schweiz betrogen hat. Und meinen Vater. Die Journalistin Sarah Fluck begibt sich zusammen mit ihrer Kollegin Vanessa Sadecky auf die Spuren des grössten Finanzbetrügers der Schweiz – der auch sie um ihr Erbe brachte.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/d5/34/2e/d5342ecd-58be-3d7c-c504-db7bf29e41e2/mza_4431514847619826418.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "15 min",
      thema: "Doku",
      art: "Seriell",
      letzte: "16. September 2022"
    },
    {
      name: "NZZaS Serien",
      link: "https://podcasts.apple.com/ch/podcast/nzzas-serien/id1478404767",
      info: "Der Ort für mehrteilige Podcast-Serien der «NZZ am Sonntag». Intelligentes Hörvergnügen zum Mitnehmen.<br/><br/>Jetzt aktuell: «Skalpell und Wahn»<br/><br/>Was tun mit psychisch Kranken, denen nichts mehr hilft? Bis zur Entdeckung der Psychopharmaka in den 1950er Jahren blieb oft nur die Leukotomie: Chirurgen öffneten die Schädeldecke und durchtrennten mit einem Metallstift Nervenbahnen im Frontalhirn.<br/>This Wachter, Theres Lüthi und Patrick Imhasly erzählen die bewegende Geschichte der Psychochirurgie in der Schweiz und was heute daraus geworden ist.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/28/2d/60/282d601e-09c2-a12d-2ba2-5b3a3019ad46/mza_1193250700732152330.jpg/626x0w.jpg",
      verlag: "NZZ",
      dauer: "15 min",
      thema: "Doku",
      art: "Seriell",
      letzte: "2. Dezember 2021"
    },
    {
      name: "Eisbrecher",
      link: "https://podcasts.apple.com/ch/podcast/eisbrecher/id1479370668",
      info: "Der Eishockey-Podcast von Tamedia.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/d3/58/11/d35811a4-7559-d091-b6c3-612370d72c0a/mza_10450966647331536292.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "60 min",
      thema: "Sport",
      art: "Episodisch",
      letzte: "17. Oktober 2023"
    },
    {
      name: "Gesprächsstoff - Berner Podcast von BZ und Der Bund",
      link: "https://podcasts.apple.com/ch/podcast/gespr%C3%A4chsstoff-berner-podcast-von-bz-und-der-bund/id1506764276",
      info: "Im neuen Berner Podcast sprechen wir über Geschichten, die unsere LeserInnen und HörerInnen bewegen. Wir nehmen Kommentare und Reaktionen auf, ordnen sie ein und entwickeln sie weiter. Jeweils zum Auftakt der Woche alle 14 Tage - moderiert von Sibylle Hartmann und Noah Fend.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/6f/2d/c6/6f2dc6c0-ecf5-bdde-3782-41fd865e039f/mza_10717231123837020070.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "30 min",
      thema: "Nachrichten",
      art: "Episodisch",
      letzte: "27. Oktober 2023"
    },
    {
      name: "BaZ – Los Emol",
      link: "https://podcasts.apple.com/ch/podcast/baz-los-emol/id1562653307",
      info: "Frisch, aktuell, volksnah: «Los emol», der Podcast der Basler Zeitung, beleuchtet jene Themen, welche die Stadt und die Region Basel bewegen. Moderiert von René Häfliger.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/36/29/ce/3629ce4c-b95a-bb44-b055-668864951e8d/mza_5103893152538964802.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "30 min",
      thema: "Nachrichten",
      art: "Episodisch",
      letzte: "19. Oktober 2023"
    },
    {
      name: "Dialogplatz",
      link: "https://podcasts.apple.com/ch/podcast/dialogplatz/id1581950764",
      info: "Der Podcast des Landboten: Alle zwei Wochen sprechen wir beim «Dialogplatz» mit einer Gästin oder einem Gast über ein Thema, das Winterthur und die Region beschäftigt.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/83/bf/59/83bf59e5-e613-8dcf-fbb1-218897968992/mza_10545781902853888540.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "45 min",
      thema: "Nachrichten",
      art: "Episodisch",
      letzte: "17. Oktober 2023"
    },
    {
      name: "Tages-Anzeigerin",
      link: "https://podcasts.apple.com/ch/podcast/tages-anzeigerin/id1598993611",
      info: "Der Podcast von Frauen, die Schlagzeilen schreiben über Frauen, die Schlagzeilen machen. Moderiert von Priska Amstutz und Annik Hosmann.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/7e/f1/79/7ef179f4-c5a3-44db-6387-51ea0e6a15e1/mza_1825135179284134703.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "45 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "10. Juli 2023"
    },
    {
      name: "Tribünengeflüster",
      link: "https://podcasts.apple.com/ch/podcast/trib%C3%BCnengefl%C3%BCster/id1624694458",
      info: "Marco Odermatt knackt alle Rekorde, das Schweizer Nationalteam verzückt die Fans und ein Dopingfall bewegt die Schweiz. Im Podcast der CH Media-Zeitungen gibt es jede Woche alle Hintergründe zum wichtigsten Sportthema der Woche.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/d6/eb/82/d6eb82d4-2358-3f2e-4b74-0735f6a83263/mza_15573691130448332050.png/626x0w.png",
      verlag: "CH Media",
      dauer: "30 min",
      thema: "Sport",
      art: "Episodisch",
      letzte: "23. Oktober 2023"
    },
    {
      name: "Heimspiel – Der Fussball-Talk",
      link: "https://podcasts.apple.com/ch/podcast/heimspiel-der-fussball-talk/id1591236912",
      info: "Der erste Schweizer Fussball-Talk. «Heimspiel» vertieft aus einer schweizerischen Perspektive die wichtigsten Themen des Fussballs: kontrovers, engagiert, humorvoll. «Heimspiel» liefert Standpunkte und Argumente.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/a9/00/d8/a900d839-1943-7bf1-25e7-d0f9f43b2762/mza_1098067433693075323.jpg/626x0w.jpg",
      verlag: "Blue",
      dauer: "45 min",
      thema: "Sport",
      art: "Episodisch",
      letzte: "19. Oktober 2023"
    },
    {
      name: "NZZ Live",
      link: "https://podcasts.apple.com/ch/podcast/nzz-live/id1709491338",
      info: "Journalismus live erleben – jetzt mit dem NZZ-Live-Podcast: damit hört ihr jeden Monat bis zu zwei Stunden der spannendsten Mitschnitte unserer Live-Veranstaltungen. Ihr begleitet interessante Gespräche mit bekannten Persönlichkeiten, moderiert von unseren Redaktorinnen und Redaktoren – und das überall, wo es Podcasts gibt.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/a6/08/5b/a6085b8c-0d2c-dd49-82c8-e1ffd40d50f9/mza_1827430352566174765.png/626x0w.png",
      verlag: "NZZ",
      dauer: "90 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "27. Oktober 2023"
    },
    {
      name: "Aus der Redaktion",
      link: "https://podcasts.apple.com/ch/podcast/aus-der-redaktion/id1347257655",
      info: "Republik - das Schweizer Digital-Magazin für Politik, Wirtschaft, Gesellschaft und Kultur – werbefrei und unabhängig.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/aa/12/56/aa12564e-9ff5-4e91-ec9a-84f41201ca88/mza_3899398320642555740.jpg/626x0w.jpg",
      verlag: "Republik",
      dauer: "30 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "27. April 2023"
    },
    // {
    //   name: "Wochenrevue",
    //   link: "https://podcasts.apple.com/ch/podcast/wochenrevue/id1501718668",
    //   info: "Hören Sie jeden Samstag in weniger als 10 min, was in der Republik los war. Wir stellen ausgewählte Beiträge der Woche vor mit Stimmen aus der Autorenschaft. Und reflektieren unsere Arbeit mit lobenden und kritischen Beiträgen aus dem Dialog. Ideal während des Kochens, beim Zugfahren oder Flanieren.",
    //   thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/59/d4/77/59d47765-300f-bae1-37c6-8324925b5844/mza_4719432935541829801.png/626x0w.png",
    //   verlag: "Republik",
    //   dauer: "15 min",
    //   thema: "Gesellschaft",
    //   art: "Episodisch",
    //   letzte: "31. Juli 2020"
    // },
    // {
    //   name: "Im Gespräch",
    //   link: "https://podcasts.apple.com/ch/podcast/im-gespr%C3%A4ch/id1521017219",
    //   info: "Der Publizist und Autor Roger de Weck lädt für die Republik wieder Gäste aus Politik, Gesellschaft, Kultur und Wirtschaft zur Debatte. Diesmal zum Hören.",
    //   thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/40/1a/58/401a58d1-dd6d-9b29-1e77-5292544df191/mza_15110919916652719800.png/626x0w.png",
    //   verlag: "Roger de Weck, Republik",
    //   dauer: "60 min",
    //   thema: "Philosophie",
    //   art: "Episodisch",
    //   letzte: "17. April 2022"
    // },
    {
      name: "Mord im Männermilieu",
      link: "https://podcasts.apple.com/ch/podcast/mord-im-m%C3%A4nnermilieu/id1603878562",
      info: "In den 1950er- und 1960er-Jahren wurden in Zürich sechs Männer ermordet, die eines verband: Sie waren schwul. Leben mussten sie im Verborgenen, tot machten sie Schlagzeilen. Eine sechsteilige Podcast-Serie über staatliche Repression und heimliche Liebe.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/58/ae/e2/58aee248-e845-1cf3-973a-96437a3964d4/mza_16639232458192039067.jpeg/626x0w.jpg",
      verlag: "Republik",
      dauer: "15 min",
      thema: "Doku",
      art: "Seriell",
      letzte: "1. April 2022"
    },
    {
      name: "Ungefiltert",
      link: "https://podcasts.apple.com/ch/podcast/ungefiltert/id1545736504",
      info: "Die Welt ist auf Distanz. Diese fünf Menschen lassen uns ganz nah ran: Andrea, Roland, Ruth, Adriana und Yannick. Das ganze Jahr nehmen sich auf, nehmen uns mit in ihren Alltag, teilen ihr Leben.<br/><br/>Ein Podcast über das Lieben, Leben und Sterben im Jahr 2020.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/8d/1d/85/8d1d85d1-27dc-dc13-33c8-9afa466621a2/mza_1275215815859078991.jpg/626x0w.jpg",
      verlag: "Republik",
      dauer: "30 min",
      thema: "Doku",
      art: "Seriell",
      letzte: "28. Dezember 2021"
    },
    {
      name: "Die gefährlichste Frau der Schweiz?",
      link: "https://podcasts.apple.com/ch/podcast/die-gef%C3%A4hrlichste-frau-der-schweiz/id1490169768",
      info: "Man nennt sie die Parkhausmörderin. Aber was, wenn sie keine Mörderin ist? Vor vier Jahren begann sich Reporter Carlos Hanimann mit der Frage zu beschäftigen: Ist Caroline H. tatsächlich eine Mörderin? Bei seinen Recherchen traf er sich mit rund fünfzig Informantinnen – mal ablehnenden, mal redseligen, mal angsterfüllten. Hanimann las sich durch öffentliche und geheime Akten und glaubte mehr als einmal, dass er nie wieder aus der Sackgasse rausfinden werde. Dies ist das Protokoll seiner Spurensuche.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/f6/d2/a7/f6d2a793-88ba-4907-6425-599c16693a32/mza_4771295683432802849.jpg/626x0w.jpg",
      verlag: "Republik",
      dauer: "30 min",
      thema: "Doku",
      art: "Seriell",
      letzte: "15. Dezember 2019"
    },
    {
      name: "Zündstoff",
      link: "https://podcasts.apple.com/ch/podcast/z%C3%BCndstoff/id1488400397",
      info: "Menschen, die sich total querstellen. Sich selber oder anderen schaden könnten, vielleicht sogar drohen. Wie umgehen mit ihnen? Als Dorf? Behörde? Familie? – Eingreifen? Ja, aber wie? Und wann? Die fünfteilige Podcast-Serie «Zündstoff» erzählt den brandaktuellen Fall von Karl, den Behörden, seiner Familie und der schwierigen Suche nach Antworten.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/73/d0/51/73d0510b-0f7c-ca03-7c64-db30ff02c22c/mza_12067835509274162278.png/626x0w.png",
      verlag: "Republik",
      dauer: "15 min",
      thema: "Doku",
      art: "Seriell",
      letzte: "23. November 2019"
    },
    // {
    //   name: "Republik Tech-Podcast",
    //   link: "https://podcasts.apple.com/ch/podcast/republik-tech-podcast/id1483436184",
    //   info: "Dieser Podcast ist für alle, die sich kritisch mit der Digitalisierung auseinandersetzen wollen. Hier verhandeln wir netzpolitische Themen, machen kleine Faktenchecks und präsentieren auch eigene Recherchen. Mit Adrienne Fichter und Nicolas Zahn.",
    //   thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/10/a9/e4/10a9e413-9af3-5cc2-3180-7fd5d7c26f69/mza_3285302882857969590.jpg/626x0w.jpg",
    //   verlag: "Republik",
    //   dauer: "30 min",
    //   thema: "Technologie",
    //   art: "Episodisch",
    //   letzte: "21. April 2020"
    // },
    {
      name: "Hinter der Schlagzeile",
      link: "https://podcasts.apple.com/ch/podcast/hinter-der-schlagzeile/id1691141431",
      info: "Wer mehr wissen will zu den wichtigsten Aktualitäten, ist hier richtig: Joëlle Weil beleuchtet zusammen mit renommierten Journalistinnen und Journalisten von CH Media aktuelle Themen und eigene Recherchen.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/55/19/48/55194889-593b-dc5c-6f8f-8a15ab52f446/mza_15862506975300205451.jpg/626x0w.jpg",
      verlag: "CH Media",
      dauer: "30 min",
      thema: "Nachrichten",
      art: "Episodisch",
      letzte: "25. Oktober 2023"
    },
    {
      name: "Wahrheit, Wein und Eisenring",
      link: "https://podcasts.apple.com/ch/podcast/wahrheit-wein-und-eisenring/id1679341088",
      info: "Radikal ehrlich: Im Talk mit Yvonne Eisenring sprechen Schweizer Prominente über Tabuthemen wie Sex, Drogen, Lohn und Tod.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/77/ea/f9/77eaf9fa-126c-fb2f-6d47-efc656b70e13/mza_11173152674727892524.jpg/626x0w.jpg",
      verlag: "CH Media",
      dauer: "",
      thema: "Gespräche",
      art: "Episodisch",
      letzte: "23. Mai 2023"
    },
    {
      name: "Passionsfrucht - Podcast",
      link: "https://podcasts.apple.com/ch/podcast/passionsfrucht-podcast/id1621711147",
      info: "Im Podcast Passionsfrucht unterhält sich Florian Pfister mit jungen Kulturschaffenden aus Ob- und Nidwalden. Sie alle vereint eines: Sie haben eine Leidenschaft für etwas, eine Passion.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts122/v4/fd/8a/63/fd8a63a9-747d-37ff-6179-a0ea6ecea471/mza_3957927400946876122.jpg/626x0w.jpg",
      verlag: "CH Media",
      dauer: "45 min",
      thema: "Gespräche",
      art: "Episodisch",
      letzte: "27. August 2023"
    },
    {
      name: "Störfrequenz",
      link: "https://podcasts.apple.com/ch/podcast/st%C3%B6rfrequenz/id1701607761",
      info: "Paula Scharrer und Olivia Merz, zwei junge Musikerinnen aus Zürich, feiern mit ihrer Indie-Band Fräulein Luise erste Erfolge. Sie spielen auf Festivals und bekommen immer mehr Aufmerksamkeit. Gleichzeitig spüren sie, dass sie anders behandelt werden als ihre männlichen Bandkollegen. In diesem Podcast wollen sie herausfinden, welchen Platz es in der Schweizer Musikwelt für sie und ihre Werte gibt. Dafür sprechen sie mit zahlreichen Schweizer Musiker*innen (Steiner & Madlaina, Big Zis, Lou Kaena, Gina Été, Soukey) und Expert*innen (Pablo Vögtli, Sirah Nying) über ihre Erlebnisse – und zeigen, wo sich etwas ändern muss.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/42/8a/22/428a2263-a206-a42b-d20a-3778c651a95f/mza_5878816429772461323.jpg/626x0w.jpg",
      verlag: "CH Media",
      dauer: "30 min",
      thema: "Doku",
      art: "Seriell",
      letzte: "15. August 2023"
    },
    {
      name: "Sags Frei",
      link: "https://podcasts.apple.com/ch/podcast/sags-frei/id1564237752",
      info: "In Sags Frei will die Journalistin Hannah Frei erfahren, wie die Menschen aus dem Seeland wirklich ticken. Sie will wissen, wie ihr Alltag aussieht, wie sie mit Konflikten und mit Niederlagen umgehen, wie und was sie denken. Ein Podcast des Bieler Tagblatt.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/24/33/44/2433442b-1dff-229e-3b2e-d6c4b18f9ed7/mza_13141502286339346641.jpg/626x0w.jpg",
      verlag: "Bieler Tagblatt",
      dauer: "45 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "19. Mai 2023"
    },
    {
      name: "Üsi Sicht",
      link: "https://podcasts.apple.com/ch/podcast/%C3%BCsi-sicht/id1620375128",
      info: "Im Podcast «Üsi Sicht» sprechen SN-Redaktorin Elena Stojkova (30) und SN-Redaktor Dario Muffler (29) über Themen, die die Region bewegen.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/bd/c6/fb/bdc6fbf7-f8c3-055c-f746-bac14981a13f/mza_13335455561618741179.jpg/626x0w.jpg",
      verlag: "Schaffhauser Nachrichten",
      dauer: "30 min",
      thema: "Nachrichten",
      art: "Episodisch",
      letzte: "17. Oktober 2023"
    },
    {
      name: "Mittendrin. Ein Schaffhauser im Ukrainekrieg",
      link: "https://podcasts.apple.com/ch/podcast/mittendrin-ein-schaffhauser-im-ukrainekrieg/id1674032016",
      info: "Ein Jahr Krieg in der Ukraine und kein Ende in Sicht. Was macht das mit einem Bauer, der alles vor Ort miterlebt? Seit einem Jahr begleiten die SN den gebürtigen Schaffhauser Moritz Stamm. In einer mehrteiligen Podcast-Serie blicken Damiana Mariani und Dario Muffler auf das Erlebte zurück und wagen einen Blick nach vorne.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/PodcastSource116/v4/e5/ac/d1/e5acd17d-379a-d011-c919-77a7345dd9d4/9e3bcb95-caee-4d17-91d6-d0901c735352.jpg/626x0w.jpg",
      verlag: "Schaffhauser Nachrichten",
      dauer: "15 min",
      thema: "Gesellschaft",
      art: "Seriell",
      letzte: "25. Februar 2023"
    },
    {
      name: "Blick: Durchblick",
      link: "https://podcasts.apple.com/ch/podcast/blick-durchblick/id1503487152",
      info: "Welche Frage an die Wissenschaft hat dich schon immer beschäftigt? Im Wissenspodcast «Durchblick – Wissen auf Wunsch» beantworten wir deine Fragen zu Gesundheit und Medizin, Technologie, Wirtschaft, Biologie, Geschichte und Geisteswissenschaften. <br/><br/>In jeder Folge nehmen sich die «Durchblick»-Hosts Daniel Fanslau und Sabine Styger ein Wissensthema vor und beleuchten es aus unterschiedlichen Blickwinkeln. Von Negativzinsen über die Umweltbilanz von spanischen Erdbeeren bis hin zur Frage, ob Menschen für die Monogamie gemacht sind und wie es mit der menschlichen Evolution weitergehen könnte.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/f5/58/d1/f558d19d-64c5-f439-942e-6838c824bf26/mza_13203216320257125184.jpg/626x0w.jpg",
      verlag: "Blick",
      dauer: "30 min",
      thema: "Wissen",
      art: "Episodisch",
      letzte: "26. Oktober 2023"
    },
    {
      name: "Blick: Die Akte Urwyler – Was kostet das Frau-Sein?",
      link: "https://podcasts.apple.com/ch/podcast/blick-die-akte-urwyler-was-kostet-das-frau-sein/id1582595564",
      info: "Der Blick-Podcast beleuchtet die Geschichte einer Frau, die alles auf ihre Karriere gesetzt hat. Einer Frau, die fast ganz oben angekommen war - und dann alles verloren hat. Natalie Urwyler ist heute eine der bekanntesten Ärztinnen der Schweiz, weil sie sich immer wieder gegen Diskriminierung gewehrt hat. Und das bis vor Gericht.<br/><br/>In diesem fünfteiligen Podcast, produziert von der Agentur «Elephant Stories», geht es um einen ungleichen Kampf, es geht um Millionen – und um diese Ärztin. Aber warum geben wir einer einzigen Person so viel Raum? Wir sind überzeugt, dass ihr Fall grössere Fragen aufwirft. Dass er zeigt, woran Gleichberechtigung in der Schweiz scheitert. Und was man dagegen unternehmen kann.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts115/v4/0a/7e/39/0a7e39f6-98f1-93ec-ab36-7758e4b0b954/mza_2190356578596222887.png/626x0w.png",
      verlag: "Blick",
      dauer: "30 min",
      thema: "Doku",
      art: "Seriell",
      letzte: "29. August 2021"
    },
    {
      name: "SODA HESCHES – Gschichte und Gschnorr",
      link: "https://podcasts.apple.com/ch/podcast/soda-hesches-gschichte-und-gschnorr/id1666260718",
      info: "«Soda by Blick» steht für News und Nützliches. Und vor allem für seine Community. Wöchentlich behandeln wir in unserem neuen Podcast Themen, direkt aus der Lebenswelt der Gen Z.<br/><br/>SODA HESCHES ist ein interaktiver Podcast von jungen Menschen für junge Menschen. Hier sorgst du für den nötigen Gesprächsstoff. Wir sind auf deine Inputs, Fragen und Tipps zu unseren wöchentlichen Fokusthemen angewiesen. Wir freuen uns auf Dich!<br/><br/>Debora (22) und Severin (28)",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/79/2a/3c/792a3c99-d9cd-50a7-7981-caa523253f1b/mza_4971854430665642676.jpg/626x0w.jpg",
      verlag: "Blick",
      dauer: "45 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "15. Oktober 2023"
    },
    {
      name: "BLICK Schwing-Podcast",
      link: "https://podcasts.apple.com/ch/podcast/blick-schwing-podcast/id1696295964",
      info: "BLICK Sport-Reporter und Schwing-Experte Marcel W. Perren diskutiert mit wechselnden Gesprächspartnern das aktuelle Geschehen auf dem Sägemehl. Analysen, Hintergründe und Anekdoten aus erster Hand!",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/c1/bf/1c/c1bf1c3d-b4da-ad81-a082-f147928dd1e1/mza_2945627635628084713.jpg/626x0w.jpg",
      verlag: "Blick",
      dauer: "60 min",
      thema: "Sport",
      art: "Episodisch",
      letzte: "22. August 2023"
    },
    {
      name: "Handelszeitung Insights",
      link: "https://podcasts.apple.com/ch/podcast/handelszeitung-insights/id1497328828",
      info: "Jede Woche liefert die Redaktion der «Handelszeitung» Hintergründe und Analysen zu einem aktuellen Thema aus Wirtschaft, Politik und Finanzen.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/40/87/ff/4087ff69-4459-5d9e-7d99-7e33b55f1c9a/mza_9041410966758619757.jpeg/626x0w.jpg",
      verlag: "Ringier Axel Springer",
      dauer: "15 min",
      thema: "Wirtschaft",
      art: "Episodisch",
      letzte: "26. Oktober 2023"
    },
    // {
    //   name: "Schöne neue Arbeitswelt",
    //   link: "https://podcasts.apple.com/ch/podcast/sch%C3%B6ne-neue-arbeitswelt/id1457163480",
    //   info: "Ein Blick auf die Wirtschaft von morgen. Wie Technologien, neue Arbeitsformen und Denkweisen die Welt verändern. Dieser Podcast pausiert zurzeit.<br/> Hosted on Acast. See acast.com/privacy for more information.",
    //   thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/3c/f0/04/3cf00487-010e-53de-b579-5eea92178dc8/mza_8995801297991647260.jpeg/626x0w.jpg",
    //   verlag: "Ringier Axel Springer",
    //   dauer: "30 min",
    //   thema: "Wirtschaft",
    //   art: "Episodisch",
    //   letzte: "19. März 2019"
    // },
    {
      name: "Handelszeitung Morning Call",
      link: "https://podcasts.apple.com/ch/podcast/handelszeitung-morning-call/id1664399746",
      info: "Jeden Montagmorgen ordnen der Ökonom Klaus Wellershoff und Markus Diem Meier, Chefredaktor der «Handelszeitung» in einem kurzen Beitrag die wichtigsten wirtschaftlichen Daten und Ereignisse der kommenden Woche ein.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/55/cf/fb/55cffb8b-1199-3711-7fb8-3be042716485/mza_2538772926595521915.png/626x0w.png",
      verlag: "Ringier Axel Springer",
      dauer: "15 min",
      thema: "Wirtschaft",
      art: "Episodisch",
      letzte: "22. Oktober 2023"
    },
    {
      name: "upbeat - der Startup-Podcast der Schweiz",
      link: "https://podcasts.apple.com/ch/podcast/upbeat-der-startup-podcast-der-schweiz/id1496579017",
      info: "Wöchentliche Interviews mit den innovativen Gründerinnen und Gründern des Landes. Gespräche über Ideen, Risiken und Nebenwirkungen. Offen, ehrlich und mit vielen Tipps für Menschen, die selber in der Startup-Welt durchstarten möchten. Der upbeat-Podcast wird zusammen mit der Credit Suisse präsentiert und ist Teil einer 360-Grad Serie - mehr Infos zu den porträtierten Unternehmen finden Sie unter handelszeitung.ch/upbeat.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/cd/2b/a4/cd2ba48c-b401-668e-50f4-e1978b3214e7/mza_1172026117710687834.jpeg/626x0w.jpg",
      verlag: "Ringier Axel Springer",
      dauer: "15 min",
      thema: "Wirtschaft",
      art: "Episodisch",
      letzte: "25. Oktober 2023"
    },
    {
      name: "Der Fall",
      link: "https://podcasts.apple.com/ch/podcast/der-fall/id1623603900",
      info: "«Der Fall» ist eine regelmässige Rubrik im Magazin «Beobachter». Darin berichten Journalistinnen und Journalisten über persönliche Schicksalsschläge. Über Fälle wie der Konflikt unter Nachbarn wegen einer vermuteten Überwachunskamera, einen Erbstreit unter Geschwistern, die bis zum Tod ihrer Eltern ein gutes Verhältnis hatten, oder über ein umstrittenes Urteile in Sachen Schweizer Niederlassungsrecht.<br/>Nun folgt «Der Fall» als Podcast, der die geschriebene Version ergänzt und erweitert. Im Gespräch mit Eric Facon erzählen die AutorInnen über ihre Fallgeschichten, darüber, wie diese Geschichten zu ihnen kamen, welche Gefühle diese menschlichen Schicksale bei ihnen auslösen. Zusätzlich klären die Beobachter-Beraterinnen Katharina Siegrist und Katrin Reichmuth juristische Fragen rund um diese Fälle und ordnen sie rechtlich ein. Verantwortlich für den Podcast ist der Journalist Eric Facon, ein langjähriger Mitarbeiter von Radio SRF.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/a9/b6/7b/a9b67b5f-68f4-9fee-010d-620b65a26a89/mza_4676499826670944547.jpeg/626x0w.jpg",
      verlag: "Ringier Axel Springer",
      dauer: "15 min",
      thema: "Gesellschaft",
      art: "Episodisch",
      letzte: "26. Oktober 2023"
    },
    {
      name: "SI.Talk - der Podcast der Schweizer Illustrierten",
      link: "https://podcasts.apple.com/ch/podcast/si-talk-der-podcast-der-schweizer-illustrierten/id1646007359",
      info: "Für die Schweizer Illustrierte bringt Sina Albisetti jede zweite Woche interessante und prominente Menschen in Plauderlaune. Ungeschminkt und ungeschnitten als Podcast, als kurzes, emotionales Video auf schweizer-illustrierte.ch.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts122/v4/8e/21/96/8e21960c-0d9b-6284-73c7-f4ba2b7ab2f6/mza_2261302490392159785.jpg/626x0w.jpg",
      verlag: "Ringier Axel Springer",
      dauer: "30 min",
      thema: "Gespräche",
      art: "Episodisch",
      letzte: "24. Oktober 2023"
    },
    {
      name: "BaZ direkt",
      link: "https://podcasts.apple.com/ch/podcast/baz-direkt/id1703537760",
      info: "Der tägliche Podcast der «Basler Zeitung». Die besten Schlagzeilen, die neusten Entwicklungen und Geschichten, die die Menschen bewegen – direkt aufs Ohr. Stets pointiert, immer empathisch, hoffentlich humorvoll. Von montags bis freitags. Jeweils um 17 Uhr.",
      thumbnail: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/be/7b/4b/be7b4b99-6206-9929-e156-45134c280c9e/mza_14493195688756893253.jpg/626x0w.jpg",
      verlag: "Tamedia",
      dauer: "15 min",
      thema: "Nachrichten",
      art: "Episodisch",
      letzte: "27. Oktober 2023"
    }
  ]